//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rocksmith2014_CDLC_Injector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rocksmith2014_CDLC_Injector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _7z {
            get {
                object obj = ResourceManager.GetObject("_7z", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _7za {
            get {
                object obj = ResourceManager.GetObject("_7za", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] core {
            get {
                object obj = ResourceManager.GetObject("core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CreateToolkitShortcut {
            get {
                object obj = ResourceManager.GetObject("CreateToolkitShortcut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] D3DX9_42 {
            get {
                object obj = ResourceManager.GetObject("D3DX9_42", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddc {
            get {
                object obj = ResourceManager.GetObject("ddc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ddc&gt;
        ///  &lt;level maxCategory=&quot;1&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;2&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;3&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;2&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;3&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;4&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddc_chords_protector {
            get {
                return ResourceManager.GetString("ddc_chords_protector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ddc&gt;
        ///  &lt;level maxCategory=&quot;1&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;2&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;3&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;2&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;3&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;4&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddc_chords_remover {
            get {
                return ResourceManager.GetString("ddc_chords_remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ddc&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory=&quot;16&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///&lt;/ddc&gt;.
        /// </summary>
        internal static string ddc_dd_remover {
            get {
                return ResourceManager.GetString("ddc_dd_remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddc_default {
            get {
                object obj = ResourceManager.GetObject("ddc_default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ddc&gt;
        ///  &lt;level maxCategory=&quot;1&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;2&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;3&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;2&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;2&quot; maxChordNotes=&quot;2&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;3&quot; maxChordNotes=&quot;2&quot;/&gt;
        ///  &lt;level maxCategory [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddc_default1 {
            get {
                return ResourceManager.GetString("ddc_default1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddc_keep_all_levels {
            get {
                object obj = ResourceManager.GetObject("ddc_keep_all_levels", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddc_merge_all_levels {
            get {
                object obj = ResourceManager.GetObject("ddc_merge_all_levels", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ICSharpCode_SharpZipLib {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_SharpZipLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] introsequence {
            get {
                object obj = ResourceManager.GetObject("introsequence", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] introsequence_original {
            get {
                object obj = ResourceManager.GetObject("introsequence_original", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     DDC is a Dynamic Difficulty Creator for Custom DownLoadable Contents
        ///    Copyright (C) 2013-2018, Chlipouni 
        ///
        ///    This program is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    This program is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without even the implied warranty  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LogoX256 {
            get {
                object obj = ResourceManager.GetObject("LogoX256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5857,Invite a Friend,,,,,フレンドを誘う,,
        ///5858,Double-check before making a purchase. It is possible to download the same content multiple times.,,,,,購入する前にもう一度ご確認ください。同じコンテンツを何度も購入することができます,,
        ///5859,You need to be signed in to Xbox LIVE for this operation. Would you like to sign in now?,,,,,この操作を実行するにはXbox LIVEにサインインする必要があります。今すぐサインインしますか？,,
        ///5860,Invite a Friend,Inviter un ami,Invitar a amigo,,,,,
        ///5861,Account,Compte,Cuenta,,,,,
        ///5862,Account,,,,,アカウント,,
        ///5863,Invite a Friend,Inviter un ami,Invitar a amigo,Invi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maingame {
            get {
                return ResourceManager.GetString("maingame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5857,Invite a Friend,,,,,フレンドを誘う,,
        ///5858,Double-check before making a purchase. It is possible to download the same content multiple times.,,,,,購入する前にもう一度ご確認ください。同じコンテンツを何度も購入することができます,,
        ///5859,You need to be signed in to Xbox LIVE for this operation. Would you like to sign in now?,,,,,この操作を実行するにはXbox LIVEにサインインする必要があります。今すぐサインインしますか？,,
        ///5860,Invite a Friend,Inviter un ami,Invitar a amigo,,,,,
        ///5861,Account,Compte,Cuenta,,,,,
        ///5862,Account,,,,,アカウント,,
        ///5863,Invite a Friend,Inviter un ami,Invitar a amigo,Invi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maingame_original {
            get {
                return ResourceManager.GetString("maingame_original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MiscUtil {
            get {
                object obj = ResourceManager.GetObject("MiscUtil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NDesk_Options {
            get {
                object obj = ResourceManager.GetObject("NDesk_Options", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NLog {
            get {
                object obj = ResourceManager.GetObject("NLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] nvdxt {
            get {
                object obj = ResourceManager.GetObject("nvdxt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] oggCut {
            get {
                object obj = ResourceManager.GetObject("oggCut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] oggdec {
            get {
                object obj = ResourceManager.GetObject("oggdec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] oggenc {
            get {
                object obj = ResourceManager.GetObject("oggenc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ookii_Dialogs {
            get {
                object obj = ResourceManager.GetObject("Ookii_Dialogs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmd.exe.
        /// </summary>
        internal static string OpenCmd {
            get {
                return ResourceManager.GetString("OpenCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] packed_codebooks {
            get {
                object obj = ResourceManager.GetObject("packed_codebooks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] packed_codebooks_aoTuV_603 {
            get {
                object obj = ResourceManager.GetObject("packed_codebooks_aoTuV_603", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PSTaskDialog {
            get {
                object obj = ResourceManager.GetObject("PSTaskDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RocksmithToolkitLib.dll uses the applications in this directory.
        ///These applications were made by developers who are not part of this project.
        ///
        ///All claims and liabilities of any misuse of the programs of this folder 
        ///should be directed to the respective developer.
        ///
        ///The files below are used to recover Rocksmith (Wwise) audio
        ///files to default .ogg file that can be used in any sound player:
        ///
        ///1. revorb.exe
        ///2. ww2ogg.exe
        ///3. packed_codebooks.bin
        ///
        ///.
        /// </summary>
        internal static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------
        ///-- DDC v3.6 (c) 2013-2018, by Chlipouni
        ///-------------------------------------------------------------
        ///
        ///DDC is a command line tool conceived to add Dynamic Difficulty Levels on Custom Downloadable Contents.
        ///
        ///Installation :
        ///--------------
        ///Just decompress the &quot;zip&quot; file in a folder of your choice.
        ///
        ///Use :
        ///-----
        ///- Open a Windows command-line interpreter
        ///- Execute the &quot;ddc.exe&quot; tool with the following parameters :
        ///
        ///  C:\ddc_v3.6&gt;ddc.exe        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string readme1 {
            get {
                return ResourceManager.GetString("readme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] revorb {
            get {
                object obj = ResourceManager.GetObject("revorb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RocksmithToolkitLib {
            get {
                object obj = ResourceManager.GetObject("RocksmithToolkitLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RocksmithToTabLib {
            get {
                object obj = ResourceManager.GetObject("RocksmithToTabLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RSMods {
            get {
                object obj = ResourceManager.GetObject("RSMods", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///    &lt;startup&gt; 
        ///        &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.7.2&quot; /&gt;
        ///    &lt;/startup&gt;
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///    &lt;/assemblyBinding&gt;
        ///  &lt;/runtime&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string RSMods_exe {
            get {
                return ResourceManager.GetString("RSMods_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RSMods1 {
            get {
                object obj = ResourceManager.GetObject("RSMods1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SevenZipSharp {
            get {
                object obj = ResourceManager.GetObject("SevenZipSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SharpConfig {
            get {
                object obj = ResourceManager.GetObject("SharpConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sltsv1_aggregategraph {
            get {
                object obj = ResourceManager.GetObject("sltsv1_aggregategraph", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] topng {
            get {
                object obj = ResourceManager.GetObject("topng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tuning_database {
            get {
                object obj = ResourceManager.GetObject("tuning_database", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ui_menu_pillar_main_database {
            get {
                object obj = ResourceManager.GetObject("ui_menu_pillar_main_database", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ui_menu_pillar_mission_database {
            get {
                object obj = ResourceManager.GetObject("ui_menu_pillar_mission_database", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.0.0 (08/02/2020).
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ww2ogg {
            get {
                object obj = ResourceManager.GetObject("ww2ogg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] X360 {
            get {
                object obj = ResourceManager.GetObject("X360", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zlib_net {
            get {
                object obj = ResourceManager.GetObject("zlib_net", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
