//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS2014_Mod_Installer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RS2014_Mod_Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _7z {
            get {
                object obj = ResourceManager.GetObject("_7z", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _7z64 {
            get {
                object obj = ResourceManager.GetObject("_7z64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _7za {
            get {
                object obj = ResourceManager.GetObject("_7za", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BouncyCastle_Crypto {
            get {
                object obj = ResourceManager.GetObject("BouncyCastle_Crypto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] core {
            get {
                object obj = ResourceManager.GetObject("core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CreateToolkitShortcut {
            get {
                object obj = ResourceManager.GetObject("CreateToolkitShortcut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddc {
            get {
                object obj = ResourceManager.GetObject("ddc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ddc&gt;
        ///  &lt;level maxCategory=&quot;1&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;2&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;3&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;2&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;3&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;4&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddc_chords_protector {
            get {
                return ResourceManager.GetString("ddc_chords_protector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ddc&gt;
        ///  &lt;level maxCategory=&quot;1&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;2&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;3&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;2&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;3&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;4&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddc_chords_remover {
            get {
                return ResourceManager.GetString("ddc_chords_remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ddc&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory=&quot;16&quot; maxChordNotes=&quot;6&quot;/&gt;
        ///&lt;/ddc&gt;.
        /// </summary>
        internal static string ddc_dd_remover {
            get {
                return ResourceManager.GetString("ddc_dd_remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddc_default {
            get {
                object obj = ResourceManager.GetObject("ddc_default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;ddc&gt;
        ///  &lt;level maxCategory=&quot;1&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;2&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;3&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;1&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;2&quot; maxChordNotes=&quot;1&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;2&quot; maxChordNotes=&quot;2&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxSubCategory= &quot;3&quot; maxChordNotes=&quot;2&quot;/&gt;
        ///  &lt;level maxCategory=&quot;4&quot; maxS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ddc_default1 {
            get {
                return ResourceManager.GetString("ddc_default1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddc_keep_all_levels {
            get {
                object obj = ResourceManager.GetObject("ddc_keep_all_levels", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ddc_merge_all_levels {
            get {
                object obj = ResourceManager.GetObject("ddc_merge_all_levels", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ICSharpCode_SharpZipLib {
            get {
                object obj = ResourceManager.GetObject("ICSharpCode_SharpZipLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     DDC is a Dynamic Difficulty Creator for Custom DownLoadable Contents
        ///    Copyright (C) 2013-2018, Chlipouni 
        ///
        ///    This program is free software: you can redistribute it and/or modify
        ///    it under the terms of the GNU General Public License as published by
        ///    the Free Software Foundation, either version 3 of the License, or
        ///    (at your option) any later version.
        ///
        ///    This program is distributed in the hope that it will be useful,
        ///    but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///    ME [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LogoX256 {
            get {
                object obj = ResourceManager.GetObject("LogoX256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Extensions_Logging_Abstractions {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Extensions_Logging_Abstractions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Microsoft_Win32_Registry {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Win32_Registry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MiscUtil {
            get {
                object obj = ResourceManager.GetObject("MiscUtil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NAudio {
            get {
                object obj = ResourceManager.GetObject("NAudio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NAudio_Asio {
            get {
                object obj = ResourceManager.GetObject("NAudio_Asio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NAudio_Core {
            get {
                object obj = ResourceManager.GetObject("NAudio_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NAudio_Midi {
            get {
                object obj = ResourceManager.GetObject("NAudio_Midi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NAudio_Wasapi {
            get {
                object obj = ResourceManager.GetObject("NAudio_Wasapi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NAudio_WinForms {
            get {
                object obj = ResourceManager.GetObject("NAudio_WinForms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NAudio_WinMM {
            get {
                object obj = ResourceManager.GetObject("NAudio_WinMM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NDesk_Options {
            get {
                object obj = ResourceManager.GetObject("NDesk_Options", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Newtonsoft_Json {
            get {
                object obj = ResourceManager.GetObject("Newtonsoft_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] NLog {
            get {
                object obj = ResourceManager.GetObject("NLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] nvdxt {
            get {
                object obj = ResourceManager.GetObject("nvdxt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] oggCut {
            get {
                object obj = ResourceManager.GetObject("oggCut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] oggdec {
            get {
                object obj = ResourceManager.GetObject("oggdec", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] oggenc {
            get {
                object obj = ResourceManager.GetObject("oggenc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ookii_Dialogs {
            get {
                object obj = ResourceManager.GetObject("Ookii_Dialogs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmd.exe.
        /// </summary>
        internal static string OpenCmd {
            get {
                return ResourceManager.GetString("OpenCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] packed_codebooks {
            get {
                object obj = ResourceManager.GetObject("packed_codebooks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] packed_codebooks_aoTuV_603 {
            get {
                object obj = ResourceManager.GetObject("packed_codebooks_aoTuV_603", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Pfim {
            get {
                object obj = ResourceManager.GetObject("Pfim", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PSTaskDialog {
            get {
                object obj = ResourceManager.GetObject("PSTaskDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------
        ///-- DDC v3.6 (c) 2013-2018, by Chlipouni
        ///-------------------------------------------------------------
        ///
        ///DDC is a command line tool conceived to add Dynamic Difficulty Levels on Custom Downloadable Contents.
        ///
        ///Installation :
        ///--------------
        ///Just decompress the &quot;zip&quot; file in a folder of your choice.
        ///
        ///Use :
        ///-----
        ///- Open a Windows command-line interpreter
        ///- Execute the &quot;ddc.exe&quot; tool with the following parameters :
        ///
        ///  C:\ddc_v3.6&gt;ddc.exe
        ///  ------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string readme {
            get {
                return ResourceManager.GetString("readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RocksmithToolkitLib.dll uses the applications in this directory.
        ///These applications were made by developers who are not part of this project.
        ///
        ///All claims and liabilities of any misuse of the programs of this folder 
        ///should be directed to the respective developer.
        ///
        ///The files below are used to recover Rocksmith (Wwise) audio
        ///files to default .ogg file that can be used in any sound player:
        ///
        ///1. revorb.exe
        ///2. ww2ogg.exe
        ///3. packed_codebooks.bin
        ///
        ///.
        /// </summary>
        internal static string readme1 {
            get {
                return ResourceManager.GetString("readme1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] revorb {
            get {
                object obj = ResourceManager.GetObject("revorb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Rocksmith2014PsarcLib {
            get {
                object obj = ResourceManager.GetObject("Rocksmith2014PsarcLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RocksmithToolkitLib {
            get {
                object obj = ResourceManager.GetObject("RocksmithToolkitLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RocksmithToTabLib {
            get {
                object obj = ResourceManager.GetObject("RocksmithToTabLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RSMods {
            get {
                object obj = ResourceManager.GetObject("RSMods", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;startup&gt;
        ///    &lt;supportedRuntime version=&quot;v4.0&quot; sku=&quot;.NETFramework,Version=v4.7.2&quot; /&gt;
        ///  &lt;/startup&gt;
        ///  &lt;runtime&gt;
        ///    &lt;assemblyBinding xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot;&gt;
        ///      &lt;dependentAssembly&gt;
        ///        &lt;assemblyIdentity name=&quot;Newtonsoft.Json&quot; publicKeyToken=&quot;30ad4fe6b2a6aeed&quot; culture=&quot;neutral&quot; /&gt;
        ///        &lt;bindingRedirect oldVersion=&quot;0.0.0.0-12.0.0.0&quot; newVersion=&quot;12.0.0.0&quot; /&gt;
        ///      &lt;/dependentAssembly&gt;
        ///    &lt;/assemblyBinding&gt;
        ///    &lt;assem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RSMods_exe {
            get {
                return ResourceManager.GetString("RSMods_exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RSMods1 {
            get {
                object obj = ResourceManager.GetObject("RSMods1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SevenZipSharp {
            get {
                object obj = ResourceManager.GetObject("SevenZipSharp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] SharpConfig {
            get {
                object obj = ResourceManager.GetObject("SharpConfig", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_AccessControl {
            get {
                object obj = ResourceManager.GetObject("System_Security_AccessControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Security_Principal_Windows {
            get {
                object obj = ResourceManager.GetObject("System_Security_Principal_Windows", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] topng {
            get {
                object obj = ResourceManager.GetObject("topng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Api {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Api", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Api_Core {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Api_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Api_Core_Enums {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Api_Core_Enums", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Api_Core_Interfaces {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Api_Core_Interfaces", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Api_Core_Models {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Api_Core_Models", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Api_Helix {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Api_Helix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Api_Helix_Models {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Api_Helix_Models", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Api_V5 {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Api_V5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Api_V5_Models {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Api_V5_Models", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Client {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Client", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Client_Enums {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Client_Enums", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Client_Models {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Client_Models", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_Communication {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_Communication", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TwitchLib_PubSub {
            get {
                object obj = ResourceManager.GetObject("TwitchLib_PubSub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ww2ogg {
            get {
                object obj = ResourceManager.GetObject("ww2ogg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wwise2010_tar {
            get {
                object obj = ResourceManager.GetObject("Wwise2010_tar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wwise2013_tar {
            get {
                object obj = ResourceManager.GetObject("Wwise2013_tar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wwise2014_tar {
            get {
                object obj = ResourceManager.GetObject("Wwise2014_tar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wwise2015_tar {
            get {
                object obj = ResourceManager.GetObject("Wwise2015_tar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wwise2016_tar {
            get {
                object obj = ResourceManager.GetObject("Wwise2016_tar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Wwise2017_tar {
            get {
                object obj = ResourceManager.GetObject("Wwise2017_tar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] X360 {
            get {
                object obj = ResourceManager.GetObject("X360", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] xinput1_3 {
            get {
                object obj = ResourceManager.GetObject("xinput1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zlib_net {
            get {
                object obj = ResourceManager.GetObject("zlib_net", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
