//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSMods.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSMods.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] introsequence_gfx {
            get {
                object obj = ResourceManager.GetObject("introsequence.gfx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5857,Invite a Friend,,,,,フレンドを誘う,,
        ///5858,Double-check before making a purchase. It is possible to download the same content multiple times.,,,,,購入する前にもう一度ご確認ください。同じコンテンツを何度も購入することができます,,
        ///5859,You need to be signed in to Xbox LIVE for this operation. Would you like to sign in now?,,,,,この操作を実行するにはXbox LIVEにサインインする必要があります。今すぐサインインしますか？,,
        ///5860,Invite a Friend,Inviter un ami,Invitar a amigo,,,,,
        ///5861,Account,Compte,Cuenta,,,,,
        ///5862,Account,,,,,アカウント,,
        ///5863,Invite a Friend,Inviter un ami,Invitar a amigo,Invi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maingame_csv {
            get {
                return ResourceManager.GetString("maingame.csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5857,Invite a Friend,,,,,フレンドを誘う,,
        ///5858,Double-check before making a purchase. It is possible to download the same content multiple times.,,,,,購入する前にもう一度ご確認ください。同じコンテンツを何度も購入することができます,,
        ///5859,You need to be signed in to Xbox LIVE for this operation. Would you like to sign in now?,,,,,この操作を実行するにはXbox LIVEにサインインする必要があります。今すぐサインインしますか？,,
        ///5860,Invite a Friend,Inviter un ami,Invitar a amigo,,,,,
        ///5861,Account,Compte,Cuenta,,,,,
        ///5862,Account,,,,,アカウント,,
        ///5863,Invite a Friend,Inviter un ami,Invitar a amigo,Invi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maingame_original_csv {
            get {
                return ResourceManager.GetString("maingame_original.csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sltsv1_aggregategraph_nt {
            get {
                object obj = ResourceManager.GetObject("sltsv1_aggregategraph.nt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tuning_database_json {
            get {
                object obj = ResourceManager.GetObject("tuning_database.json", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
