// DLL Hijack. Do NOT remove this line!
#include "Proxy.hpp"
#include "D3DInfo.h"
#include "Tests.hpp"
#include "CC/ControlServer.hpp"
#include "Mods/Enumeration.hpp"
#include "Mods/CustomSongTitles.hpp"
#include "Mods/CollectColors.hpp"
#include "Mods/GuitarSkeletons.hpp"
#include "Mods/GuitarSpeak.hpp"
#include "Mods/DisableControllers.hpp"
#include "Mods/Midi.hpp"
#include "Mods/VolumeControl.hpp"
#include "Mods/LaunchOnExternalMonitor.hpp"
#include "Mods/VoiceOverControl.hpp"
#include "Mods/RiffRepeater.hpp"
#include "Mods/AudioDevices.hpp"
#include "Mods/BugPrevention.hpp"
#include "Mods/TrueTuning.hpp"
#include "Mods/Loft.hpp"
#include "Menu.hpp"
#include "Keyboard.hpp"
#include "QualityOfLife.hpp"
#include "Keybindings.hpp"
#include "Twitch.hpp"
#include "ModManager.hpp"

inline std::string selectedUser = "";
