#pragma once

#define RSMODS_VERSION_MAJOR 1
#define RSMODS_VERSION_MINOR 2
#define RSMODS_VERSION_PATCH 8
#define RSMODS_VERSION_BUILD 4

#define RSMODS_STRINGIFY_IMPL(value) #value
#define RSMODS_STRINGIFY(value) RSMODS_STRINGIFY_IMPL(value)

#define RSMODS_VERSION_COMMA \
	RSMODS_VERSION_MAJOR, \
	RSMODS_VERSION_MINOR, \
	RSMODS_VERSION_PATCH, \
	RSMODS_VERSION_BUILD

#define RSMODS_VERSION_STRING \
	RSMODS_STRINGIFY(RSMODS_VERSION_MAJOR) "." \
	RSMODS_STRINGIFY(RSMODS_VERSION_MINOR) "." \
	RSMODS_STRINGIFY(RSMODS_VERSION_PATCH) "." \
	RSMODS_STRINGIFY(RSMODS_VERSION_BUILD)

#define RSMODS_BUILD_VERSION_STRING \
	RSMODS_VERSION_STRING "-" RSMODS_GIT_HASH
